spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    defer-datasource-initialization: true
  datasource:
    url: jdbc:mariadb://20.249.216.53:3306/blog
    username: redgreen
    password: 1234

  server:
    port: 80

#    url: jdbc:h2:mem:testdb
#  h2:
#    console:
#      enabled: true